import React, { useState } from 'react'
import { FiSearch } from "react-icons/fi";
import SearchDropDown from "./shared/searchdropdown.js";
import SearchDropDownCommunes from "./shared/searchDropDownCommunes.js";

import "./searchBar.css";



function SearchBar() {
  const [ baladiyat, setBaladiyat] = useState([]);


  const types = ["Terrain", "Terrain Agricole", "Appartement", "Maison", "Bungalow"];
  const currentType = types[0];

  return (
    <div className='searchbar'>

      <SearchDropDown items={types} defaultValue="Select type" onChange={() => { }}  />
      <div class="wrapper">
  <input type="text" />
  <FiSearch className='icon' />
</div>

<SearchDropDown items={wilayas} defaultValue="Select Wilaya" 
  onChange={(event) => {
    const nb = wilayas.indexOf(event.target.value);

    const filtered = communes.filter(function (element) { return element.wilaya === (nb + 1); })

    setBaladiyat(filtered);
  }} />

      <SearchDropDownCommunes items={baladiyat}   defaultValue="Select commune" onChange={() => { }} />


      <div className='date_picker'>
        <h2>Max date</h2>
        <input type="date" />
      </div>



      <div className='baths_beds'>
        <h2>Baths</h2>
        <input type='number' />
      </div>
      <div className='baths_beds'>
        <h2>Beds</h2>
        <input type="number" />
      </div>

      <button >Search</button>

    </div>

  )
}

export default SearchBar;

 
var communes = [
  { name: "Adrar", wilaya: 1 },
  { name: "Akabli", wilaya: 1 },
  { name: "Aougrout", wilaya: 1 },
  { name: "Aoulef", wilaya: 1 },
  { name: "Bordj Badji Mokhtar", wilaya: 1 },
  { name: "Bouda", wilaya: 1 },
  { name: "Charouine", wilaya: 1 },
  { name: "Deldoul", wilaya: 1 },
  { name: "Fenoughil", wilaya: 1 },
  { name: "In Zghmir", wilaya: 1 },
  { name: "Ksar Kaddour", wilaya: 1 },
  { name: "Metarfa", wilaya: 1 },
  { name: "Ouled Ahmed Tammi", wilaya: 1 },
  { name: "Ouled Aïssa", wilaya: 1 },
  { name: "Ouled Saïd", wilaya: 1 },
  { name: "Reggane", wilaya: 1 },
  { name: "Sali", wilaya: 1 },
  { name: "Sebaa", wilaya: 1 },
  { name: "Talmine", wilaya: 1 },
  { name: "Tamantit", wilaya: 1 },
  { name: "Tamekten", wilaya: 1 },
  { name: "Tamest", wilaya: 1 },
  { name: "Timiaouine", wilaya: 1 },
  { name: "Timimoun", wilaya: 1 },
  { name: "Tinerkouk", wilaya: 1 },
  { name: "Tit", wilaya: 1 },
  { name: "Tsabit", wilaya: 1 },
  { name: "Zaouiet Kounta", wilaya: 1 },
  { name: "Abou El Hassan", wilaya: 2 },
  { name: "Aïn Merane", wilaya: 2 },
  { name: "Bénairia", wilaya: 2 },
  { name: "Beni Bouateb", wilaya: 2 },
  { name: "Beni Haoua", wilaya: 2 },
  { name: "Beni Rached", wilaya: 2 },
  { name: "Boukadir", wilaya: 2 },
  { name: "Bouzeghaia", wilaya: 2 },
  { name: "Breira", wilaya: 2 },
  { name: "Chettia", wilaya: 2 },
  { name: "Chlef", wilaya: 2 },
  { name: "Dahra", wilaya: 2 },
  { name: "El Hadjadj", wilaya: 2 },
  { name: "El Karimia", wilaya: 2 },
  { name: "El Marsa", wilaya: 2 },
  { name: "Harchoun", wilaya: 2 },
  { name: "Harenfa", wilaya: 2 },
  { name: "Labiod Medjadja", wilaya: 2 },
  { name: "Moussadek", wilaya: 2 },
  { name: "Oued Fodda", wilaya: 2 },
  { name: "Oued Goussine", wilaya: 2 },
  { name: "Oued Sly", wilaya: 2 },
  { name: "Ouled Abbes", wilaya: 2 },
  { name: "Ouled Ben Abdelkader", wilaya: 2 },
  { name: "Ouled Fares", wilaya: 2 },
  { name: "Oum Drou", wilaya: 2 },
  { name: "Sendjas", wilaya: 2 },
  { name: "Sidi Abderrahmane", wilaya: 2 },
  { name: "Sidi Akkacha", wilaya: 2 },
  { name: "Sobha", wilaya: 2 },
  { name: "Tadjena", wilaya: 2 },
  { name: "Talassa", wilaya: 2 },
  { name: "Taougrite", wilaya: 2 },
  { name: "Ténès", wilaya: 2 },
  { name: "Zeboudja", wilaya: 2 },
  { name: "Laghouat", wilaya: 3 },
  { name: "Ksar El Hirane", wilaya: 3 },
  { name: "Bennasser Benchohra", wilaya: 3 },
  { name: "Sidi Makhlouf", wilaya: 3 },
  { name: "Hassi Delaa", wilaya: 3 },
  { name: "Hassi R'Mel", wilaya: 3 },
  { name: "Aïn Madhi", wilaya: 3 },
  { name: "Tadjemout", wilaya: 3 },
  { name: "Kheneg", wilaya: 3 },
  { name: "Gueltat Sidi Saad", wilaya: 3 },
  { name: "Aïn Sidi Ali", wilaya: 3 },
  { name: "Beidha", wilaya: 3 },
  { name: "Brida", wilaya: 3 },
  { name: "El Ghicha", wilaya: 3 },
  { name: "Hadj Mechri", wilaya: 3 },
  { name: "Sebgag", wilaya: 3 },
  { name: "Taouila", wilaya: 3 },
  { name: "Tadjrouna", wilaya: 3 },
  { name: "Aflou", wilaya: 3 },
  { name: "El Assafia", wilaya: 3 },
  { name: "Oued Morra", wilaya: 3 },
  { name: "Oued M'Zi", wilaya: 3 },
  { name: "El Houaita", wilaya: 3 },
  { name: "Sidi Bouzid", wilaya: 3 },
  { name: "Oum el Bouaghi", wilaya: 4 },
  { name: "Aïn Béïda", wilaya: 4 },
  { name: "Aïn M'lila", wilaya: 4 },
  { name: "Behir Chergui", wilaya: 4 },
  { name: "El Amiria", wilaya: 4 },
  { name: "Sigus", wilaya: 4 },
  { name: "El Belala", wilaya: 4 },
  { name: "Aïn Babouche", wilaya: 4 },
  { name: "Berriche", wilaya: 4 },
  { name: "Ouled Hamla", wilaya: 4 },
  { name: "Dhalaa", wilaya: 4 },
  { name: "Aïn Kercha", wilaya: 4 },
  { name: "Hanchir Toumghani", wilaya: 4 },
  { name: "El Djazia", wilaya: 4 },
  { name: "Aïn Diss", wilaya: 4 },
  { name: "Fkirina", wilaya: 4 },
  { name: "Souk Naamane", wilaya: 4 },
  { name: "Zorg", wilaya: 4 },
  { name: "El Fedjouz Boughrara Saoudi", wilaya: 4 },
  { name: "Ouled Zouaï", wilaya: 4 },
  { name: "Bir Chouhada", wilaya: 4 },
  { name: "Ksar Sbahi", wilaya: 4 },
  { name: "Oued Nini", wilaya: 4 },
  { name: "Meskiana", wilaya: 4 },
  { name: "Aïn Fakroun", wilaya: 4 },
  { name: "Rahia", wilaya: 4 },
  { name: "Aïn Zitoun", wilaya: 4 },
  { name: "Ouled Gacem", wilaya: 4 },
  { name: "El Harmilia", wilaya: 4 },
  { name: "Batna", wilaya: 5 },
  { name: "Ghassira", wilaya: 5 },
  { name: "Maafa", wilaya: 5 },
  { name: "Merouana", wilaya: 5 },
  { name: "Seriana", wilaya: 5 },
  { name: "Menaa", wilaya: 5 },
  { name: "El Madher", wilaya: 5 },
  { name: "Tazoult", wilaya: 5 },
  { name: "N'Gaous", wilaya: 5 },
  { name: "Guigba", wilaya: 5 },
  { name: "Inoughissen", wilaya: 5 },
  { name: "Ouyoun El Assafir", wilaya: 5 },
  { name: "Djerma", wilaya: 5 },
  { name: "Bitam", wilaya: 5 },
  { name: "Abdelkader Azil", wilaya: 5 },
  { name: "Arris", wilaya: 5 },
  { name: "Kimmel", wilaya: 5 },
  { name: "Tilatou", wilaya: 5 },
  { name: "Aïn Djasser", wilaya: 5 },
  { name: "Ouled Sellam", wilaya: 5 },
  { name: "Tigherghar", wilaya: 5 },
  { name: "Aïn Yagout", wilaya: 5 },
  { name: "Sefiane", wilaya: 5 },
  { name: "Fesdis", wilaya: 5 },
  { name: "Rahbat", wilaya: 5 },
  { name: "Tighanimine", wilaya: 5 },
  { name: "Lemsane", wilaya: 5 },
  { name: "Ksar Bellezma", wilaya: 5 },
  { name: "Seggana", wilaya: 5 },
  { name: "Ichmoul", wilaya: 5 },
  { name: "Foum Toub", wilaya: 5 },
  { name: "Ben Foudhala El Hakania", wilaya: 5 },
  { name: "Oued El Ma", wilaya: 5 },
  { name: "Talkhamt", wilaya: 5 },
  { name: "Bouzina", wilaya: 5 },
  { name: "Chemora", wilaya: 5 },
  { name: "Oued Chaaba", wilaya: 5 },
  { name: "Taxlent", wilaya: 5 },
  { name: "Gosbat", wilaya: 5 },
  { name: "Ouled Aouf", wilaya: 5 },
  { name: "Boumaguer", wilaya: 5 },
  { name: "Barika", wilaya: 5 },
  { name: "Djezar", wilaya: 5 },
  { name: "T'Kout", wilaya: 5 },
  { name: "Aïn Touta", wilaya: 5 },
  { name: "Hidoussa", wilaya: 5 },
  { name: "Teniet El Abed", wilaya: 5 },
  { name: "Oued Taga", wilaya: 5 },
  { name: "Ouled Fadel", wilaya: 5 },
  { name: "Timgad", wilaya: 5 },
  { name: "Ras El Aioun", wilaya: 5 },
  { name: "Chir", wilaya: 5 },
  { name: "Ouled Si Slimane", wilaya: 5 },
  { name: "Zanat El Beida", wilaya: 5 },
  { name: "M'doukel", wilaya: 5 },
  { name: "Ouled Ammar", wilaya: 5 },
  { name: "El Hassi", wilaya: 5 },
  { name: "Lazrou", wilaya: 5 },
  { name: "Boumia", wilaya: 5 },
  { name: "Boulhilat", wilaya: 5 },
  { name: "Larbaâ", wilaya: 5 },
  { name: "Béjaïa", wilaya: 6 },
  { name: "Amizour", wilaya: 6 },
  { name: "Ferraoun", wilaya: 6 },
  { name: "Taourirt Ighil", wilaya: 6 },
  { name: "Chellata", wilaya: 6 },
  { name: "Tamokra", wilaya: 6 },
  { name: "Timezrit", wilaya: 6 },
  { name: "Souk El Ténine", wilaya: 6 },
  { name: "M'cisna", wilaya: 6 },
  { name: "Tinabdher", wilaya: 6 },
  { name: "Tichy", wilaya: 6 },
  { name: "Semaoun", wilaya: 6 },
  { name: "Kendira", wilaya: 6 },
  { name: "Tifra", wilaya: 6 },
  { name: "Ighram", wilaya: 6 },
  { name: "Amalou", wilaya: 6 },
  { name: "Ighil Ali", wilaya: 6 },
  { name: "Fenaïa Ilmaten", wilaya: 6 },
  { name: "Toudja", wilaya: 6 },
  { name: "Darguina", wilaya: 6 },
  { name: "Sidi-Ayad", wilaya: 6 },
  { name: "Aokas", wilaya: 6 },
  { name: "Beni Djellil", wilaya: 6 },
  { name: "Adekar", wilaya: 6 },
  { name: "Akbou", wilaya: 6 },
  { name: "Seddouk", wilaya: 6 },
  { name: "Tazmalt", wilaya: 6 },
  { name: "Aït-R'zine", wilaya: 6 },
  { name: "Chemini", wilaya: 6 },
  { name: "Souk-Oufella", wilaya: 6 },
  { name: "Taskriout", wilaya: 6 },
  { name: "Tibane", wilaya: 6 },
  { name: "Tala Hamza", wilaya: 6 },
  { name: "Barbacha", wilaya: 6 },
  { name: "Beni Ksila", wilaya: 6 },
  { name: "Ouzellaguen", wilaya: 6 },
  { name: "Bouhamza", wilaya: 6 },
  { name: "Beni Mellikeche", wilaya: 6 },
  { name: "Sidi-Aïch", wilaya: 6 },
  { name: "El Kseur", wilaya: 6 },
  { name: "Melbou", wilaya: 6 },
  { name: "Akfadou", wilaya: 6 },
  { name: "Leflaye", wilaya: 6 },
  { name: "Kherrata", wilaya: 6 },
  { name: "Draâ El-Kaïd", wilaya: 6 },
  { name: "Tamridjet", wilaya: 6 },
  { name: "Aït-Smail", wilaya: 6 },
  { name: "Boukhelifa", wilaya: 6 },
  { name: "Tizi N'Berber", wilaya: 6 },
  { name: "Beni Maouche", wilaya: 6 },
  { name: "Oued Ghir", wilaya: 6 },
  { name: "Boudjellil", wilaya: 6 },
  { name: "Aïn Naga", wilaya: 7 },
  { name: "Aïn Zaatout", wilaya: 7 },
  { name: "Besbes", wilaya: 7 },
  { name: "Biskra", wilaya: 7 },
  { name: "Bordj Ben Azzouz", wilaya: 7 },
  { name: "Bouchagroune", wilaya: 7 },
  { name: "Branis", wilaya: 7 },
  { name: "Chetma", wilaya: 7 },
  { name: "Djemorah", wilaya: 7 },
  { name: "Doucen", wilaya: 7 },
  { name: "Ech Chaïba", wilaya: 7 },
  { name: "El Feidh", wilaya: 7 },
  { name: "El Ghrous", wilaya: 7 },
  { name: "El Hadjeb", wilaya: 7 },
  { name: "El Haouch", wilaya: 7 },
  { name: "El Kantara", wilaya: 7 },
  { name: "El Mizaraa", wilaya: 7 },
  { name: "El Outaya", wilaya: 7 },
  { name: "Foughala", wilaya: 7 },
  { name: "Khenguet Sidi Nadji", wilaya: 7 },
  { name: "Lichana", wilaya: 7 },
  { name: "Lioua", wilaya: 7 },
  { name: "M'Chouneche", wilaya: 7 },
  { name: "Mekhadma", wilaya: 7 },
  { name: "M'Lili", wilaya: 7 },
  { name: "Ouled Djellal", wilaya: 7 },
  { name: "Oumache", wilaya: 7 },
  { name: "Ourlal", wilaya: 7 },
  { name: "Ras El Miaad", wilaya: 7 },
  { name: "Sidi Khaled", wilaya: 7 },
  { name: "Sidi Okba", wilaya: 7 },
  { name: "Tolga", wilaya: 7 },
  { name: "Zeribet El Oued", wilaya: 7 },
  { name: "Béchar", wilaya: 8 },
  { name: "Erg Ferradj", wilaya: 8 },
  { name: "Ouled Khoudir", wilaya: 8 },
  { name: "Meridja", wilaya: 8 },
  { name: "Timoudi", wilaya: 8 },
  { name: "Lahmar", wilaya: 8 },
  { name: "Béni Abbès", wilaya: 8 },
  { name: "Beni Ikhlef", wilaya: 8 },
  { name: "Mechraa Houari Boumedienne", wilaya: 8 },
  { name: "Kenadsa", wilaya: 8 },
  { name: "Igli", wilaya: 8 },
  { name: "Tabelbala", wilaya: 8 },
  { name: "Taghit", wilaya: 8 },
  { name: "El Ouata", wilaya: 8 },
  { name: "Boukais", wilaya: 8 },
  { name: "Mougheul", wilaya: 8 },
  { name: "Abadla", wilaya: 8 },
  { name: "Kerzaz", wilaya: 8 },
  { name: "Ksabi", wilaya: 8 },
  { name: "Tamtert", wilaya: 8 },
  { name: "Beni Ounif", wilaya: 8 },
  { name: "Blida", wilaya: 9 },
  { name: "Chebli", wilaya: 9 },
  { name: "Bouinan", wilaya: 9 },
  { name: "Oued Alleug", wilaya: 9 },
  { name: "Ouled Yaïch", wilaya: 9 },
  { name: "Chréa", wilaya: 9 },
  { name: "El Affroun", wilaya: 9 },
  { name: "Chiffa", wilaya: 9 },
  { name: "Hammam Melouane", wilaya: 9 },
  { name: "Benkhelil", wilaya: 9 },
  { name: "Soumaa", wilaya: 9 },
  { name: "Mouzaia", wilaya: 9 },
  { name: "Souhane", wilaya: 9 },
  { name: "Meftah", wilaya: 9 },
  { name: "Ouled Slama", wilaya: 9 },
  { name: "Boufarik", wilaya: 9 },
  { name: "Larbaa", wilaya: 9 },
  { name: "Oued Djer", wilaya: 9 },
  { name: "Beni Tamou", wilaya: 9 },
  { name: "Bouarfa", wilaya: 9 },
  { name: "Beni Mered", wilaya: 9 },
  { name: "Ouled Mimoun", wilaya: 13 },
  { name: "Amieur", wilaya: 13 },
  { name: "Aïn Youcef", wilaya: 13 },
  { name: "Zenata", wilaya: 13 },
  { name: "Beni Snous", wilaya: 13 },
  { name: "Bab El Assa", wilaya: 13 },
  { name: "Dar Yaghmouracene", wilaya: 13 },
  { name: "Fellaoucene", wilaya: 13 },
  { name: "Azails", wilaya: 13 },
  { name: "Sebaa Chioukh", wilaya: 13 },
  { name: "Terny Beni Hdiel", wilaya: 13 },
  { name: "Bensekrane", wilaya: 13 },
  { name: "Aïn Nehala", wilaya: 13 },
  { name: "Hennaya", wilaya: 13 },
  { name: "Maghnia", wilaya: 13 },
  { name: "Hammam Boughrara", wilaya: 13 },
  { name: "Souahlia", wilaya: 13 },
  { name: "MSirda Fouaga", wilaya: 13 },
  { name: "Aïn Fetah", wilaya: 13 },
  { name: "El Aricha", wilaya: 13 },
  { name: "Souk Tlata", wilaya: 13 },
  { name: "Sidi Abdelli", wilaya: 13 },
  { name: "Sebdou", wilaya: 13 },
  { name: "Beni Ouarsous", wilaya: 13 },
  { name: "Sidi Medjahed", wilaya: 13 },
  { name: "Beni Boussaid", wilaya: 13 },
  { name: "Marsa Ben M'Hidi", wilaya: 13 },
  { name: "Nedroma", wilaya: 13 },
  { name: "Sidi Djillali", wilaya: 13 },
  { name: "Beni Bahdel", wilaya: 13 },
  { name: "El Bouihi", wilaya: 13 },
  { name: "Honaïne", wilaya: 13 },
  { name: "Tienet", wilaya: 13 },
  { name: "Ouled Riyah", wilaya: 13 },
  { name: "Bouhlou", wilaya: 13 },
  { name: "Beni Khellad", wilaya: 13 },
  { name: "Aïn Ghoraba", wilaya: 13 },
  { name: "Chetouane", wilaya: 13 },
  { name: "Mansourah", wilaya: 13 },
  { name: "Beni Semiel", wilaya: 13 },
  { name: "Aïn Kebira", wilaya: 13 },
  { name: "Aïn Bouchekif", wilaya: 14 },
  { name: "Aïn Deheb", wilaya: 14 },
  { name: "Aïn El Hadid", wilaya: 14 },
  { name: "Aïn Kermes", wilaya: 14 },
  { name: "Aïn Zarit", wilaya: 14 },
  { name: "Bougara", wilaya: 14 },
  { name: "Chehaima", wilaya: 14 },
  { name: "Dahmouni", wilaya: 14 },
  { name: "Djebilet Rosfa", wilaya: 14 },
  { name: "Djillali Ben Amar", wilaya: 14 },
  { name: "Faidja", wilaya: 14 },
  { name: "Frenda", wilaya: 14 },
  { name: "Guertoufa", wilaya: 14 },
  { name: "Hamadia", wilaya: 14 },
  { name: "Ksar Chellala", wilaya: 14 },
  { name: "Madna", wilaya: 14 },
  { name: "Mahdia", wilaya: 14 },
  { name: "Mechraa Safa", wilaya: 14 },
  { name: "Medrissa", wilaya: 14 },
  { name: "Medroussa", wilaya: 14 },
  { name: "Meghila", wilaya: 14 },
  { name: "Mellakou", wilaya: 14 },
  { name: "Nadorah", wilaya: 14 },
  { name: "Naima", wilaya: 14 },
  { name: "Oued Lilli", wilaya: 14 },
  { name: "Rahouia", wilaya: 14 },
  { name: "Rechaiga", wilaya: 14 },
  { name: "Sebaine", wilaya: 14 },
  { name: "Sebt", wilaya: 14 },
  { name: "Serghine", wilaya: 14 },
  { name: "Si Abdelghani", wilaya: 14 },
  { name: "Sidi Abderahmane", wilaya: 14 },
  { name: "Sidi Ali Mellal", wilaya: 14 },
  { name: "Sidi Bakhti", wilaya: 14 },
  { name: "Sidi Hosni", wilaya: 14 },
  { name: "Sougueur", wilaya: 14 },
  { name: "Tagdemt", wilaya: 14 },
  { name: "Takhemaret", wilaya: 14 },
  { name: "Tiaret", wilaya: 14 },
  { name: "Tidda", wilaya: 14 },
  { name: "Tousnina", wilaya: 14 },
  { name: "Zmalet El Emir Abdelkader", wilaya: 14 },
  { name: "Tizi Ouzou", wilaya: 15 },
  { name: "Ain El Hammam", wilaya: 15 },
  { name: "Akbil", wilaya: 15 },
  { name: "Freha", wilaya: 15 },
  { name: "Souamaâ", wilaya: 15 },
  { name: "Mechtras", wilaya: 15 },
  { name: "Irdjen", wilaya: 15 },
  { name: "Timizart", wilaya: 15 },
  { name: "Makouda", wilaya: 15 },
  { name: "Draâ El Mizan", wilaya: 15 },
  { name: "Tizi Gheniff", wilaya: 15 },
  { name: "Bounouh", wilaya: 15 },
  { name: "Aït Chafâa", wilaya: 15 },
  { name: "Frikat", wilaya: 15 },
  { name: "Beni Aïssi", wilaya: 15 },
  { name: "Beni Zmenzer", wilaya: 15 },
  { name: "Iferhounène", wilaya: 15 },
  { name: "Azazga", wilaya: 15 },
  { name: "Illoula Oumalou", wilaya: 15 },
  { name: "Yakouren", wilaya: 15 },
  { name: "Larbaâ Nath Irathen", wilaya: 15 },
  { name: "Tizi Rached", wilaya: 15 },
  { name: "Zekri", wilaya: 15 },
  { name: "Ouaguenoun", wilaya: 15 },
  { name: "Aïn Zaouia", wilaya: 15 },
  { name: "M'Kira", wilaya: 15 },
  { name: "Aït Yahia", wilaya: 15 },
  { name: "Aït Mahmoud", wilaya: 15 },
  { name: "Mâatkas", wilaya: 15 },
  { name: "Aït Boumahdi", wilaya: 15 },
  { name: "Abi Youcef", wilaya: 15 },
  { name: "Beni Douala", wilaya: 15 },
  { name: "Illilten", wilaya: 15 },
  { name: "Bouzguen", wilaya: 15 },
  { name: "Aït Aggouacha", wilaya: 15 },
  { name: "Ouadhia", wilaya: 15 },
  { name: "Azeffoun", wilaya: 15 },
  { name: "Tigzirt", wilaya: 15 },
  { name: "Djebel Aissa Mimoun", wilaya: 15 },
  { name: "Boghni", wilaya: 15 },
  { name: "Ifigha", wilaya: 15 },
  { name: "Aït Oumalou", wilaya: 15 },
  { name: "Tirmitine", wilaya: 15 },
  { name: "Akerrou", wilaya: 15 },
  { name: "Yatafen", wilaya: 15 },
  { name: "Beni Ziki", wilaya: 15 },
  { name: "Draâ Ben Khedda", wilaya: 15 },
  { name: "Ouacif", wilaya: 15 },
  { name: "Idjeur", wilaya: 15 },
  { name: "Mekla", wilaya: 15 },
  { name: "Tizi N'Tleta", wilaya: 15 },
  { name: "Beni Yenni", wilaya: 15 },
  { name: "Aghribs", wilaya: 15 },
  { name: "Iflissen", wilaya: 15 },
  { name: "Boudjima", wilaya: 15 },
  { name: "Aït Yahia Moussa", wilaya: 15 },
  { name: "Souk El Thenine", wilaya: 15 },
  { name: "Aït Khellili", wilaya: 15 },
  { name: "Sidi Namane", wilaya: 15 },
  { name: "Iboudraren", wilaya: 15 },
  { name: "Agouni Gueghrane", wilaya: 15 },
  { name: "Mizrana", wilaya: 15 },
  { name: "Imsouhel", wilaya: 15 },
  { name: "Tadmaït", wilaya: 15 },
  { name: "Aït Bouadou", wilaya: 15 },
  { name: "Assi Youcef", wilaya: 15 },
  { name: "Aït Toudert", wilaya: 15 },
  { name: "Alger-Centre", wilaya: 16 },
  { name: "El Madania", wilaya: 16 },
  { name: "Belouizdad", wilaya: 16 },
  { name: "Bab El Oued", wilaya: 16 },
  { name: "Bologhine", wilaya: 16 },
  { name: "Oued Koriche", wilaya: 16 },
  { name: "Bir Mourad Raïs", wilaya: 16 },
  { name: "Sidi M'Hamed", wilaya: 16 },
  { name: "Casbah", wilaya: 16 },
  { name: "El Biar", wilaya: 16 },
  { name: "Bouzareah", wilaya: 16 },
  { name: "Birkhadem", wilaya: 16 },
  { name: "El Harrach", wilaya: 16 },
  { name: "Baraki", wilaya: 16 },
  { name: "Oued Smar", wilaya: 16 },
  { name: "Bourouba", wilaya: 16 },
  { name: "Hussein Dey", wilaya: 16 },
  { name: "Kouba", wilaya: 16 },
  { name: "Bachdjerrah", wilaya: 16 },
  { name: "Dar El Beïda", wilaya: 16 },
  { name: "Bab Ezzouar", wilaya: 16 },
  { name: "Ben Aknoun", wilaya: 16 },
  { name: "Dely Ibrahim", wilaya: 16 },
  { name: "El Hammamet", wilaya: 16 },
  { name: "Raïs Hamidou", wilaya: 16 },
  { name: "Djasr Kasentina", wilaya: 16 },
  { name: "El Mouradia", wilaya: 16 },
  { name: "Hydra", wilaya: 16 },
  { name: "Mohammadia", wilaya: 16 },
  { name: "Bordj El Kiffan", wilaya: 16 },
  { name: "El Magharia", wilaya: 16 },
  { name: "Beni Messous", wilaya: 16 },
  { name: "Les Eucalyptus", wilaya: 16 },
  { name: "Birtouta", wilaya: 16 },
  { name: "Tessala El Merdja", wilaya: 16 },
  { name: "Ouled Chebel", wilaya: 16 },
  { name: "Sidi Moussa", wilaya: 16 },
  { name: "Aïn Taya", wilaya: 16 },
  { name: "Bordj El Bahri", wilaya: 16 },
  { name: "El Marsa", wilaya: 16 },
  { name: "H'raoua", wilaya: 16 },
  { name: "Rouïba", wilaya: 16 },
  { name: "Reghaïa", wilaya: 16 },
  { name: "Aïn Benian", wilaya: 16 },
  { name: "Staoueli", wilaya: 16 },
  { name: "Zeralda", wilaya: 16 },
  { name: "Mahelma", wilaya: 16 },
  { name: "Rahmania", wilaya: 16 },
  { name: "Souidania", wilaya: 16 },
  { name: "Cheraga", wilaya: 16 },
  { name: "Ouled Fayet", wilaya: 16 },
  { name: "El Achour", wilaya: 16 },
  { name: "Draria", wilaya: 16 },
  { name: "Douera", wilaya: 16 },
  { name: "Baba Hassen", wilaya: 16 },
  { name: "Khraicia", wilaya: 16 },
  { name: "Saoula", wilaya: 16 },
  { name: "Aïn Chouhada", wilaya: 17 },
  { name: "Aïn El Ibel", wilaya: 17 },
  { name: "Aïn Feka", wilaya: 17 },
  { name: "Aïn Maabed", wilaya: 17 },
  { name: "Aïn Oussara", wilaya: 17 },
  { name: "Amourah", wilaya: 17 },
  { name: "Benhar", wilaya: 17 },
  { name: "Beni Yagoub", wilaya: 17 },
  { name: "Birine", wilaya: 17 },
  { name: "Bouira Lahdab", wilaya: 17 },
  { name: "Charef", wilaya: 17 },
  { name: "Dar Chioukh", wilaya: 17 },
  { name: "Deldoul", wilaya: 17 },
  { name: "Djelfa", wilaya: 17 },
  { name: "Douis", wilaya: 17 },
  { name: "El Guedid", wilaya: 17 },
  { name: "El Idrissia", wilaya: 17 },
  { name: "El Khemis", wilaya: 17 },
  { name: "Faidh El Botma", wilaya: 17 },
  { name: "Guernini", wilaya: 17 },
  { name: "Guettara", wilaya: 17 },
  { name: "Had-Sahary", wilaya: 17 },
  { name: "Hassi Bahbah", wilaya: 17 },
  { name: "Hassi El Euch", wilaya: 17 },
  { name: "Hassi Fedoul", wilaya: 17 },
  { name: "Messaad", wilaya: 17 },
  { name: "M'Liliha", wilaya: 17 },
  { name: "Moudjebara", wilaya: 17 },
  { name: "Oum Laadham", wilaya: 17 },
  { name: "Sed Rahal", wilaya: 17 },
  { name: "Selmana", wilaya: 17 },
  { name: "Sidi Baizid", wilaya: 17 },
  { name: "Sidi Ladjel", wilaya: 17 },
  { name: "Tadmit", wilaya: 17 },
  { name: "Zaafrane", wilaya: 17 },
  { name: "Zaccar", wilaya: 17 },
  { name: "Jijel", wilaya: 18 },
  { name: "Eraguene", wilaya: 18 },
  { name: "El Aouana", wilaya: 18 },
  { name: "Ziama Mansouriah", wilaya: 18 },
  { name: "Taher", wilaya: 18 },
  { name: "Emir Abdelkader", wilaya: 18 },
  { name: "Chekfa", wilaya: 18 },
  { name: "Chahna", wilaya: 18 },
  { name: "El Milia", wilaya: 18 },
  { name: "Sidi Maarouf", wilaya: 18 },
  { name: "Settara", wilaya: 18 },
  { name: "El Ancer", wilaya: 18 },
  { name: "Sidi Abdelaziz", wilaya: 18 },
  { name: "Kaous", wilaya: 18 },
  { name: "Ghebala", wilaya: 18 },
  { name: "Bouraoui Belhadef", wilaya: 18 },
  { name: "Djimla", wilaya: 18 },
  { name: "Selma Benziada", wilaya: 18 },
  { name: "Boucif Ouled Askeur", wilaya: 18 },
  { name: "El Kennar Nouchfi", wilaya: 18 },
  { name: "Ouled Yahia Khedrouche", wilaya: 18 },
  { name: "Boudriaa Ben Yadjis", wilaya: 18 },
  { name: "Kheïri Oued Adjoul", wilaya: 18 },
  { name: "Texenna", wilaya: 18 },
  { name: "Djemaa Beni Habibi", wilaya: 18 },
  { name: "Bordj Tahar", wilaya: 18 },
  { name: "Ouled Rabah", wilaya: 18 },
  { name: "Ouadjana", wilaya: 18 },
  { name: "Aïn Abessa", wilaya: 19 },
  { name: "Aïn Arnat", wilaya: 19 },
  { name: "Aïn Azel", wilaya: 19 },
  { name: "Aïn El Kebira", wilaya: 19 },
  { name: "Aïn Lahdjar", wilaya: 19 },
  { name: "Aïn Legraj", wilaya: 19 },
  { name: "Aïn Oulmene", wilaya: 19 },
  { name: "Aïn Roua", wilaya: 19 },
  { name: "Aïn Sebt", wilaya: 19 },
  { name: "Aït Naoual Mezada", wilaya: 19 },
  { name: "Aït Tizi", wilaya: 19 },
  { name: "Amoucha", wilaya: 19 },
  { name: "Babor", wilaya: 19 },
  { name: "Bazer Sakhra", wilaya: 19 },
  { name: "Beidha Bordj", wilaya: 19 },
  { name: "Belaa", wilaya: 19 },
  { name: "Beni Aziz", wilaya: 19 },
  { name: "Beni Chebana", wilaya: 19 },
  { name: "Beni Fouda", wilaya: 19 },
  { name: "Beni Hocine", wilaya: 19 },
  { name: "Beni Mouhli", wilaya: 19 },
  { name: "Beni Ouartilene", wilaya: 19 },
  { name: "Bir El Arch", wilaya: 19 },
  { name: "Bir Haddada", wilaya: 19 },
  { name: "Bouandas", wilaya: 19 },
  { name: "Bougaa", wilaya: 19 },
  { name: "Bousselam", wilaya: 19 },
  { name: "Boutaleb", wilaya: 19 },
  { name: "Dehamcha", wilaya: 19 },
  { name: "Djemila", wilaya: 19 },
  { name: "Draa Kebila", wilaya: 19 },
  { name: "El Eulma", wilaya: 19 },
  { name: "El Ouldja", wilaya: 19 },
  { name: "El Ouricia", wilaya: 19 },
  { name: "Guellal", wilaya: 19 },
  { name: "Guelta Zerka", wilaya: 19 },
  { name: "Guenzet", wilaya: 19 },
  { name: "Guidjel", wilaya: 19 },
  { name: "Hamma", wilaya: 19 },
  { name: "Hammam Guergour", wilaya: 19 },
  { name: "Hammam Soukhna", wilaya: 19 },
  { name: "Harbil", wilaya: 19 },
  { name: "Ksar El Abtal", wilaya: 19 },
  { name: "Maaouia", wilaya: 19 },
  { name: "Maoklane", wilaya: 19 },
  { name: "Mezloug", wilaya: 19 },
  { name: "Oued El Barad", wilaya: 19 },
  { name: "Ouled Addouane", wilaya: 19 },
  { name: "Ouled Sabor", wilaya: 19 },
  { name: "Ouled Si Ahmed", wilaya: 19 },
  { name: "Ouled Tebben", wilaya: 19 },
  { name: "Rasfa", wilaya: 19 },
  { name: "Salah Bey", wilaya: 19 },
  { name: "Serdj El Ghoul", wilaya: 19 },
  { name: "Sétif", wilaya: 19 },
  { name: "Tachouda", wilaya: 19 },
  { name: "Talaifacene", wilaya: 19 },
  { name: "Taya", wilaya: 19 },
  { name: "Tella", wilaya: 19 },
  { name: "Tizi N'Bechar", wilaya: 19 },
  { name: "Aïn El Hadjar", wilaya: 20 },
  { name: "Aïn Sekhouna", wilaya: 20 },
  { name: "Aïn Soltane", wilaya: 20 },
  { name: "Doui Thabet", wilaya: 20 },
  { name: "El Hassasna", wilaya: 20 },
  { name: "Hounet", wilaya: 20 },
  { name: "Maamora", wilaya: 20 },
  { name: "Moulay Larbi", wilaya: 20 },
  { name: "Ouled Brahim", wilaya: 20 },
  { name: "Ouled Khaled", wilaya: 20 },
  { name: "Saïda", wilaya: 20 },
  { name: "Sidi Ahmed", wilaya: 20 },
  { name: "Sidi Amar", wilaya: 20 },
  { name: "Sidi Boubekeur", wilaya: 20 },
  { name: "Tircine", wilaya: 20 },
  { name: "Youb", wilaya: 20 },
  { name: "Aïn Bouziane", wilaya: 21 },
  { name: "Aïn Charchar", wilaya: 21 },
  { name: "Aïn Kechra", wilaya: 21 },
  { name: "Aïn Zouit", wilaya: 21 },
  { name: "Azzaba", wilaya: 21 },
  { name: "Bekkouche Lakhdar", wilaya: 21 },
  { name: "Bin El Ouiden", wilaya: 21 },
  { name: "Ben Azzouz", wilaya: 21 },
  { name: "Beni Bechir", wilaya: 21 },
  { name: "Beni Oulbane", wilaya: 21 },
  { name: "Beni Zid", wilaya: 21 },
  { name: "Bouchtata", wilaya: 21 },
  { name: "Cheraia", wilaya: 21 },
  { name: "Collo", wilaya: 21 },
  { name: "Djendel Saadi Mohamed", wilaya: 21 },
  { name: "El Ghedir", wilaya: 21 },
  { name: "El Hadaiek", wilaya: 21 },
  { name: "El Harrouch", wilaya: 21 },
  { name: "El Marsa", wilaya: 21 },
  { name: "Emdjez Edchich", wilaya: 21 },
  { name: "Es Sebt", wilaya: 21 },
  { name: "Filfila", wilaya: 21 },
  { name: "Hamadi Krouma", wilaya: 21 },
  { name: "Kanoua", wilaya: 21 },
  { name: "Kerkera", wilaya: 21 },
  { name: "Kheneg Mayoum", wilaya: 21 },
  { name: "Oued Zehour", wilaya: 21 },
  { name: "Ouldja Boulballout", wilaya: 21 },
  { name: "Ouled Attia", wilaya: 21 },
  { name: "Ouled Hbaba", wilaya: 21 },
  { name: "Oum Toub", wilaya: 21 },
  { name: "Ramdane Djamel", wilaya: 21 },
  { name: "Salah Bouchaour", wilaya: 21 },
  { name: "Sidi Mezghiche", wilaya: 21 },
  { name: "Skikda", wilaya: 21 },
  { name: "Tamalous", wilaya: 21 },
  { name: "Zerdaza", wilaya: 21 },
  { name: "Zito", wilaya: 21 },
  { name: "Aïn Adden", wilaya: 22 },
  { name: "Aïn El Berd", wilaya: 22 },
  { name: "Aïn Kada", wilaya: 22 },
  { name: "Aïn Thrid", wilaya: 22 },
  { name: "Aïn Tindamine", wilaya: 22 },
  { name: "Amarnas", wilaya: 22 },
  { name: "Badredine El Mokrani", wilaya: 22 },
  { name: "Belarbi", wilaya: 22 },
  { name: "Ben Badis", wilaya: 22 },
  { name: "Benachiba Chelia", wilaya: 22 },
  { name: "Bir El Hammam", wilaya: 22 },
  { name: "Boudjebaa El Bordj", wilaya: 22 },
  { name: "Boukhanafis", wilaya: 22 },
  { name: "Chettouane Belaila", wilaya: 22 },
  { name: "Dhaya", wilaya: 22 },
  { name: "El Haçaiba", wilaya: 22 },
  { name: "Hassi Dahou", wilaya: 22 },
  { name: "Hassi Zehana", wilaya: 22 },
  { name: "Lamtar", wilaya: 22 },
  { name: "Makedra", wilaya: 22 },
  { name: "Marhoum", wilaya: 22 },
  { name: "M'Cid", wilaya: 22 },
  { name: "Merine", wilaya: 22 },
  { name: "Mezaourou", wilaya: 22 },
  { name: "Mostefa Ben Brahim", wilaya: 22 },
  { name: "Moulay Slissen", wilaya: 22 },
  { name: "Oued Sebaa", wilaya: 22 },
  { name: "Oued Sefioun", wilaya: 22 },
  { name: "Oued Taourira", wilaya: 22 },
  { name: "Ras El Ma", wilaya: 22 },
  { name: "Redjem Demouche", wilaya: 22 },
  { name: "Sehala Thaoura", wilaya: 22 },
  { name: "Sfisef", wilaya: 22 },
  { name: "Sidi Ali Benyoub", wilaya: 22 },
  { name: "Sidi Ali Boussidi", wilaya: 22 },
  { name: "Sidi Bel Abbes", wilaya: 22 },
  { name: "Sidi Brahim", wilaya: 22 },
  { name: "Sidi Chaib", wilaya: 22 },
  { name: "Sidi Dahou de Zairs", wilaya: 22 },
  { name: "Sidi Hamadouche", wilaya: 22 },
  { name: "Sidi Khaled", wilaya: 22 },
  { name: "Sidi Lahcene", wilaya: 22 },
  { name: "Sidi Yacoub", wilaya: 22 },
  { name: "Tabia", wilaya: 22 },
  { name: "Tafissour", wilaya: 22 },
  { name: "Taoudmout", wilaya: 22 },
  { name: "Teghalimet", wilaya: 22 },
  { name: "Telagh", wilaya: 22 },
  { name: "Tenira", wilaya: 22 },
  { name: "Tessala", wilaya: 22 },
  { name: "Tilmouni", wilaya: 22 },
  { name: "Zerouala", wilaya: 22 },
  { name: "Annaba", wilaya: 23 },
  { name: "Barrahel", wilaya: 23 },
  { name: "El Hadjar", wilaya: 23 },
  { name: "Eulma", wilaya: 23 },
  { name: "El Bouni", wilaya: 23 },
  { name: "Oued El Aneb", wilaya: 23 },
  { name: "Cheurfa", wilaya: 23 },
  { name: "Seraïdi", wilaya: 23 },
  { name: "Aïn Berda", wilaya: 23 },
  { name: "Chetaïbi", wilaya: 23 },
  { name: "Sidi Amar", wilaya: 23 },
  { name: "Treat", wilaya: 23 },
  { name: "Aïn Ben Beida", wilaya: 24 },
  { name: "Aïn Larbi", wilaya: 24 },
  { name: "Aïn Makhlouf", wilaya: 24 },
  { name: "Aïn Reggada", wilaya: 24 },
  { name: "Aïn Sandel", wilaya: 24 },
  { name: "Belkheir", wilaya: 24 },
  { name: "Ben Djerrah", wilaya: 24 },
  { name: "Beni Mezline", wilaya: 24 },
  { name: "Bordj Sabat", wilaya: 24 },
  { name: "Bouhachana", wilaya: 24 },
  { name: "Bouhamdane", wilaya: 24 },
  { name: "Bouati Mahmoud", wilaya: 24 },
  { name: "Bouchegouf", wilaya: 24 },
  { name: "Boumahra Ahmed", wilaya: 24 },
  { name: "Dahouara", wilaya: 24 },
  { name: "Djeballah Khemissi", wilaya: 24 },
  { name: "El Fedjoudj", wilaya: 24 },
  { name: "Guellat Bou Sbaa", wilaya: 24 },
  { name: "Guelma", wilaya: 24 },
  { name: "Hammam Debagh", wilaya: 24 },
  { name: "Hammam N'Bail", wilaya: 24 },
  { name: "Héliopolis", wilaya: 24 },
  { name: "Houari Boumédiène", wilaya: 24 },
  { name: "Khezarra", wilaya: 24 },
  { name: "Medjez Amar", wilaya: 24 },
  { name: "Medjez Sfa", wilaya: 24 },
  { name: "Nechmaya", wilaya: 24 },
  { name: "Oued Cheham", wilaya: 24 },
  { name: "Oued Fragha", wilaya: 24 },
  { name: "Oued Zenati", wilaya: 24 },
  { name: "Ras El Agba", wilaya: 24 },
  { name: "Roknia", wilaya: 24 },
  { name: "Sellaoua Announa", wilaya: 24 },
  { name: "Tam", wilaya: 24 },
  { name: "Aïn Abid", wilaya: 25 },
  { name: "Aïn Smara", wilaya: 25 },
  { name: "Beni Hamiden", wilaya: 25 },
  { name: "Constantine", wilaya: 25 },
  { name: "Didouche Mourad", wilaya: 25 },
  { name: "El Khroub", wilaya: 25 },
  { name: "Hamma Bouziane", wilaya: 25 },
  { name: "Ibn Badis", wilaya: 25 },
  { name: "Ibn Ziad", wilaya: 25 },
  { name: "Messaoud Boudjriou", wilaya: 25 },
  { name: "Ouled Rahmoune", wilaya: 25 },
  { name: "Zighoud Youcef", wilaya: 25 },
  { name: "Aïn Boucif", wilaya: 26 },
  { name: "Aïn Ouksir", wilaya: 26 },
  { name: "Aissaouia", wilaya: 26 },
  { name: "Aziz", wilaya: 26 },
  { name: "Baata", wilaya: 26 },
  { name: "Benchicao", wilaya: 26 },
  { name: "Beni Slimane", wilaya: 26 },
  { name: "Berrouaghia", wilaya: 26 },
  { name: "Bir Ben Laabed", wilaya: 26 },
  { name: "Boghar", wilaya: 26 },
  { name: "Bou Aiche", wilaya: 26 },
  { name: "Bouaichoune", wilaya: 26 },
  { name: "Bouchrahil", wilaya: 26 },
  { name: "Boughezoul", wilaya: 26 },
  { name: "Bouskene", wilaya: 26 },
  { name: "Chahbounia", wilaya: 26 },
  { name: "Chellalet El Adhaoura", wilaya: 26 },
  { name: "Cheniguel", wilaya: 26 },
  { name: "Derrag", wilaya: 26 },
  { name: "Deux Bassins", wilaya: 26 },
  { name: "Djouab", wilaya: 26 },
  { name: "Draa Essamar", wilaya: 26 },
  { name: "El Azizia", wilaya: 26 },
  { name: "El Guelb El Kebir", wilaya: 26 },
  { name: "El Hamdania", wilaya: 26 },
  { name: "El Omaria", wilaya: 26 },
  { name: "El Ouinet", wilaya: 26 },
  { name: "Hannacha", wilaya: 26 },
  { name: "Kef Lakhdar", wilaya: 26 },
  { name: "Khams Djouamaa", wilaya: 26 },
  { name: "Ksar Boukhari", wilaya: 26 },
  { name: "Meghraoua", wilaya: 26 },
  { name: "Médéa", wilaya: 26 },
  { name: "Moudjbar", wilaya: 26 },
  { name: "Meftaha", wilaya: 26 },
  { name: "Mezerana", wilaya: 26 },
  { name: "Mihoub", wilaya: 26 },
  { name: "Ouamri", wilaya: 26 },
  { name: "Oued Harbil", wilaya: 26 },
  { name: "Ouled Antar", wilaya: 26 },
  { name: "Ouled Bouachra", wilaya: 26 },
  { name: "Ouled Brahim", wilaya: 26 },
  { name: "Ouled Deide", wilaya: 26 },
  { name: "Ouled Hellal", wilaya: 26 },
  { name: "Ouled Maaref", wilaya: 26 },
  { name: "Oum El Djalil", wilaya: 26 },
  { name: "Ouzera", wilaya: 26 },
  { name: "Rebaia", wilaya: 26 },
  { name: "Saneg", wilaya: 26 },
  { name: "Sedraia", wilaya: 26 },
  { name: "Seghouane", wilaya: 26 },
  { name: "Si Mahdjoub", wilaya: 26 },
  { name: "Sidi Damed", wilaya: 26 },
  { name: "Sidi Errabia", wilaya: 26 },
  { name: "Sidi Naamane", wilaya: 26 },
  { name: "Sidi Zahar", wilaya: 26 },
  { name: "Sidi Ziane", wilaya: 26 },
  { name: "Souagui", wilaya: 26 },
  { name: "Tablat", wilaya: 26 },
  { name: "Tafraout", wilaya: 26 },
  { name: "Tamesguida", wilaya: 26 },
  { name: "Tizi Mahdi", wilaya: 26 },
  { name: "Tlatet Eddouar", wilaya: 26 },
  { name: "Zoubiria", wilaya: 26 },
  { name: "Abdelmalek Ramdane", wilaya: 27 },
  { name: "Achaacha", wilaya: 27 },
  { name: "Aïn Boudinar", wilaya: 27 },
  { name: "Aïn Nouïssy", wilaya: 27 },
  { name: "Aïn Sidi Cherif", wilaya: 27 },
  { name: "Aïn Tedles", wilaya: 27 },
  { name: "Blad Touahria", wilaya: 27 },
  { name: "Bouguirat", wilaya: 27 },
  { name: "El Hassaine", wilaya: 27 },
  { name: "Fornaka", wilaya: 27 },
  { name: "Hadjadj", wilaya: 27 },
  { name: "Hassi Mameche", wilaya: 27 },
  { name: "Khadra", wilaya: 27 },
  { name: "Kheireddine", wilaya: 27 },
  { name: "Mansourah", wilaya: 27 },
  { name: "Mesra", wilaya: 27 },
  { name: "Mazagran", wilaya: 27 },
  { name: "Mostaganem", wilaya: 27 },
  { name: "Nekmaria", wilaya: 27 },
  { name: "Oued El Kheir", wilaya: 27 },
  { name: "Ouled Boughalem", wilaya: 27 },
  { name: "Ouled Maallah", wilaya: 27 },
  { name: "Safsaf", wilaya: 27 },
  { name: "Sayada", wilaya: 27 },
  { name: "Sidi Ali", wilaya: 27 },
  { name: "Sidi Belattar", wilaya: 27 },
  { name: "Sidi Lakhdar", wilaya: 27 },
  { name: "Sirat", wilaya: 27 },
  { name: "Souaflia", wilaya: 27 },
  { name: "Sour", wilaya: 27 },
  { name: "Stidia", wilaya: 27 },
  { name: "Tazgait", wilaya: 27 },
  { name: "Aïn El Hadjel", wilaya: 28 },
  { name: "Aïn El Melh", wilaya: 28 },
  { name: "Aïn Errich", wilaya: 28 },
  { name: "Aïn Fares", wilaya: 28 },
  { name: "Aïn Khadra", wilaya: 28 },
  { name: "Belaiba", wilaya: 28 },
  { name: "Ben Srour", wilaya: 28 },
  { name: "Beni Ilmane", wilaya: 28 },
  { name: "Benzouh", wilaya: 28 },
  { name: "Berhoum", wilaya: 28 },
  { name: "Bir Foda", wilaya: 28 },
  { name: "Bou-Saâda", wilaya: 28 },
  { name: "Bouti Sayah", wilaya: 28 },
  { name: "Chellal", wilaya: 28 },
  { name: "Dehahna", wilaya: 28 },
  { name: "Djebel Messaad", wilaya: 28 },
  { name: "El Hamel", wilaya: 28 },
  { name: "El Houamed", wilaya: 28 },
  { name: "Hammam Dhalaa", wilaya: 28 },
  { name: "Khettouti Sed El Djir", wilaya: 28 },
  { name: "Khoubana", wilaya: 28 },
  { name: "Maadid", wilaya: 28 },
  { name: "Maarif", wilaya: 28 },
  { name: "Magra", wilaya: 28 },
  { name: "M'Cif", wilaya: 28 },
  { name: "Medjedel", wilaya: 28 },
  { name: "Mohammed Boudiaf", wilaya: 28 },
  { name: "M'Sila", wilaya: 28 },
  { name: "M'Tarfa", wilaya: 28 },
  { name: "Ouanougha", wilaya: 28 },
  { name: "Ouled Addi Guebala", wilaya: 28 },
  { name: "Ouled Atia", wilaya: 28 },
  { name: "Ouled Derradj", wilaya: 28 },
  { name: "Ouled Madhi", wilaya: 28 },
  { name: "Ouled Mansour", wilaya: 28 },
  { name: "Ouled Sidi Brahim", wilaya: 28 },
  { name: "Ouled Slimane", wilaya: 28 },
  { name: "Oultem", wilaya: 28 },
  { name: "Sidi Aïssa", wilaya: 28 },
  { name: "Sidi Ameur", wilaya: 28 },
  { name: "Sidi Hadjeres", wilaya: 28 },
  { name: "Sidi M'Hamed", wilaya: 28 },
  { name: "Slim", wilaya: 28 },
  { name: "Souamaa", wilaya: 28 },
  { name: "Tamsa", wilaya: 28 },
  { name: "Tarmount", wilaya: 28 },
  { name: "Zarz", wilaya: 28 },
  { name: "Aïn Fares", wilaya: 29 },
  { name: "Aïn Fekan", wilaya: 29 },
  { name: "Aïn Ferah", wilaya: 29 },
  { name: "Aïn Fras", wilaya: 29 },
  { name: "Alaimia", wilaya: 29 },
  { name: "Aouf", wilaya: 29 },
  { name: "Beniane", wilaya: 29 },
  { name: "Bou Hanifia", wilaya: 29 },
  { name: "Bou Henni", wilaya: 29 },
  { name: "Chorfa", wilaya: 29 },
  { name: "El Bordj", wilaya: 29 },
  { name: "El Gaada", wilaya: 29 },
  { name: "El Ghomri", wilaya: 29 },
  { name: "El Guettana", wilaya: 29 },
  { name: "El Keurt", wilaya: 29 },
  { name: "El Menaouer", wilaya: 29 },
  { name: "Ferraguig", wilaya: 29 },
  { name: "Froha", wilaya: 29 },
  { name: "Gharrous", wilaya: 29 },
  { name: "Guerdjoum", wilaya: 29 },
  { name: "Ghriss", wilaya: 29 },
  { name: "Hachem", wilaya: 29 },
  { name: "Hacine", wilaya: 29 },
  { name: "Khalouia", wilaya: 29 },
  { name: "Makdha", wilaya: 29 },
  { name: "Mamounia", wilaya: 29 },
  { name: "Maoussa", wilaya: 29 },
  { name: "Mascara", wilaya: 29 },
  { name: "Matemore", wilaya: 29 },
  { name: "Mocta Douz", wilaya: 29 },
  { name: "Mohammadia", wilaya: 29 },
  { name: "Nesmoth", wilaya: 29 },
  { name: "Oggaz", wilaya: 29 },
  { name: "Oued El Abtal", wilaya: 29 },
  { name: "Oued Taria", wilaya: 29 },
  { name: "Ras Ain Amirouche", wilaya: 29 },
  { name: "Sedjerara", wilaya: 29 },
  { name: "Sehailia", wilaya: 29 },
  { name: "Sidi Abdeldjebar", wilaya: 29 },
  { name: "Sidi Abdelmoumen", wilaya: 29 },
  { name: "Sidi Kada", wilaya: 29 },
  { name: "Sidi Boussaid", wilaya: 29 },
  { name: "Sig", wilaya: 29 },
  { name: "Tighennif", wilaya: 29 },
  { name: "Tizi", wilaya: 29 },
  { name: "Zahana", wilaya: 29 },
  { name: "Zel", wilaya: 29 },
  { name: "Aïn Beida", wilaya: 30 },
  { name: "Benaceur", wilaya: 30 },
  { name: "Blidet Amor", wilaya: 30 },
  { name: "El Allia", wilaya: 30 },
  { name: "El Borma", wilaya: 30 },
  { name: "El Hadjira", wilaya: 30 },
  { name: "Hassi Ben Abdellah", wilaya: 30 },
  { name: "Hassi Messaoud", wilaya: 30 },
  { name: "Megarine", wilaya: 30 },
  { name: "M'Naguer", wilaya: 30 },
  { name: "Nezla", wilaya: 30 },
  { name: "N'Goussa", wilaya: 30 },
  { name: "Ouargla", wilaya: 30 },
  { name: "Rouissat", wilaya: 30 },
  { name: "Sidi Khouiled", wilaya: 30 },
  { name: "Sidi Slimane", wilaya: 30 },
  { name: "Taibet", wilaya: 30 },
  { name: "Tamacine", wilaya: 30 },
  { name: "Tebesbest", wilaya: 30 },
  { name: "Touggourt", wilaya: 30 },
  { name: "Zaouia El Abidia", wilaya: 30 },
  { name: "Oran", wilaya: 31 },
  { name: "Gdyel", wilaya: 31 },
  { name: "Bir El Djir", wilaya: 31 },
  { name: "Hassi Bounif", wilaya: 31 },
  { name: "Es Senia", wilaya: 31 },
  { name: "Arzew", wilaya: 31 },
  { name: "Bethioua", wilaya: 31 },
  { name: "Marsat El Hadjadj", wilaya: 31 },
  { name: "Aïn El Turk", wilaya: 31 },
  { name: "El Ançor", wilaya: 31 },
  { name: "Oued Tlelat", wilaya: 31 },
  { name: "Tafraoui", wilaya: 31 },
  { name: "Sidi Chami", wilaya: 31 },
  { name: "Boufatis", wilaya: 31 },
  { name: "Mers El Kébir", wilaya: 31 },
  { name: "Bou-Sfer", wilaya: 31 },
  { name: "El Kerma", wilaya: 31 },
  { name: "El Braya", wilaya: 31 },
  { name: "Hassi Ben Okba", wilaya: 31 },
  { name: "Ben Freha", wilaya: 31 },
  { name: "Hassi Mefsoukh", wilaya: 31 },
  { name: "Sidi Benyebka", wilaya: 31 },
  { name: "Misserghin", wilaya: 31 },
  { name: "Boutlelis", wilaya: 31 },
  { name: "Aïn El Kerma", wilaya: 31 },
  { name: "Aïn El Bia", wilaya: 31 },
  { name: "El Bayadh", wilaya: 32 },
  { name: "Rogassa", wilaya: 32 },
  { name: "Stitten", wilaya: 32 },
  { name: "Brezina", wilaya: 32 },
  { name: "Ghassoul", wilaya: 32 },
  { name: "Boualem", wilaya: 32 },
  { name: "El Abiodh Sidi Cheikh", wilaya: 32 },
  { name: "Aïn El Orak", wilaya: 32 },
  { name: "Arbaouat", wilaya: 32 },
  { name: "Bougtoub", wilaya: 32 },
  { name: "El Kheiter", wilaya: 32 },
  { name: "Kef El Ahmar", wilaya: 32 },
  { name: "Boussemghoun", wilaya: 32 },
  { name: "Chellala", wilaya: 32 },
  { name: "Kraakda", wilaya: 32 },
  { name: "El Bnoud", wilaya: 32 },
  { name: "Cheguig", wilaya: 32 },
  { name: "Sidi Ameur", wilaya: 32 },
  { name: "El Mehara", wilaya: 32 },
  { name: "Tousmouline", wilaya: 32 },
  { name: "Sidi Slimane", wilaya: 32 },
  { name: "Sidi Tifour", wilaya: 32 },
  { name: "Illizi", wilaya: 33 },
  { name: "Djanet", wilaya: 33 },
  { name: "Debdeb", wilaya: 33 },
  { name: "Bordj Omar Driss", wilaya: 33 },
  { name: "Bordj El Haouas", wilaya: 33 },
  { name: "In Amenas", wilaya: 33 },
  { name: "Aïn Taghrout", wilaya: 34 },
  { name: "Aïn Tesra", wilaya: 34 },
  { name: "Belimour", wilaya: 34 },
  { name: "Ben Daoud", wilaya: 34 },
  { name: "Bir Kasdali", wilaya: 34 },
  { name: "Bordj Bou Arreridj", wilaya: 34 },
  { name: "Bordj Ghédir", wilaya: 34 },
  { name: "Bordj Zemoura", wilaya: 34 },
  { name: "Colla", wilaya: 34 },
  { name: "Djaafra", wilaya: 34 },
  { name: "El Ach", wilaya: 34 },
  { name: "El Achir", wilaya: 34 },
  { name: "El Anseur", wilaya: 34 },
  { name: "El Hamadia", wilaya: 34 },
  { name: "El Main", wilaya: 34 },
  { name: "El M'hir", wilaya: 34 },
  { name: "Ghilassa", wilaya: 34 },
  { name: "Haraza", wilaya: 34 },
  { name: "Hasnaoua", wilaya: 34 },
  { name: "Khelil", wilaya: 34 },
  { name: "Ksour", wilaya: 34 },
  { name: "Mansoura", wilaya: 34 },
  { name: "Medjana", wilaya: 34 },
  { name: "Ouled Brahem", wilaya: 34 },
  { name: "Ouled Dahmane", wilaya: 34 },
  { name: "Ouled Sidi Brahim", wilaya: 34 },
  { name: "Rabta", wilaya: 34 },
  { name: "Ras El Oued", wilaya: 34 },
  { name: "Sidi Embarek", wilaya: 34 },
  { name: "Tefreg", wilaya: 34 },
  { name: "Taglait", wilaya: 34 },
  { name: "Teniet En Nasr", wilaya: 34 },
  { name: "Tassameurt", wilaya: 34 },
  { name: "Tixter", wilaya: 34 },
  { name: "Afir", wilaya: 35 },
  { name: "Ammal", wilaya: 35 },
  { name: "Baghlia", wilaya: 35 },
  { name: "Ben Choud", wilaya: 35 },
  { name: "Beni Amrane", wilaya: 35 },
  { name: "Bordj Menaiel", wilaya: 35 },
  { name: "Boudouaou", wilaya: 35 },
  { name: "Boudouaou-El-Bahri", wilaya: 35 },
  { name: "Boumerdes", wilaya: 35 },
  { name: "Bouzegza Keddara", wilaya: 35 },
  { name: "Chabet el Ameur", wilaya: 35 },
  { name: "Corso", wilaya: 35 },
  { name: "Dellys", wilaya: 35 },
  { name: "Djinet", wilaya: 35 },
  { name: "El Kharrouba", wilaya: 35 },
  { name: "Hammedi", wilaya: 35 },
  { name: "Issers", wilaya: 35 },
  { name: "Khemis El-Khechna", wilaya: 35 },
  { name: "Larbatache", wilaya: 35 },
  { name: "Leghata", wilaya: 35 },
  { name: "Naciria", wilaya: 35 },
  { name: "Ouled Aissa", wilaya: 35 },
  { name: "Ouled Hedadj", wilaya: 35 },
  { name: "Ouled Moussa", wilaya: 35 },
  { name: "Si Mustapha", wilaya: 35 },
  { name: "Sidi Daoud", wilaya: 35 },
  { name: "Souk El Had", wilaya: 35 },
  { name: "Taourga", wilaya: 35 },
  { name: "Thenia", wilaya: 35 },
  { name: "Tidjelabine", wilaya: 35 },
  { name: "Timezrit", wilaya: 35 },
  { name: "Zemm", wilaya: 35 },
  { name: "Aïn El Assel", wilaya: 36 },
  { name: "Aïn Kerma", wilaya: 36 },
  { name: "Asfour", wilaya: 36 },
  { name: "Ben Mehidi", wilaya: 36 },
  { name: "Berrihane", wilaya: 36 },
  { name: "Besbes", wilaya: 36 },
  { name: "Bougous", wilaya: 36 },
  { name: "Bouhadjar", wilaya: 36 },
  { name: "Bouteldja", wilaya: 36 },
  { name: "Chebaita Mokhtar", wilaya: 36 },
  { name: "Chefia", wilaya: 36 },
  { name: "Chihani", wilaya: 36 },
  { name: "Dréan", wilaya: 36 },
  { name: "Echatt", wilaya: 36 },
  { name: "El Aioun", wilaya: 36 },
  { name: "El Kala", wilaya: 36 },
  { name: "El Tarf", wilaya: 36 },
  { name: "Hammam Beni Salah", wilaya: 36 },
  { name: "Lac des Oiseaux", wilaya: 36 },
  { name: "Oued Zitoun", wilaya: 36 },
  { name: "Raml Souk", wilaya: 36 },
  { name: "Souarekh", wilaya: 36 },
  { name: "Zerizer", wilaya: 36 },
  { name: "Zitouna", wilaya: 36 },
  { name: "Oum el Assel", wilaya: 37 },
  { name: "Tindouf", wilaya: 37 },
  { name: "Ammari", wilaya: 38 },
  { name: "Beni Chaib", wilaya: 38 },
  { name: "Beni Lahcene", wilaya: 38 },
  { name: "Boucaid", wilaya: 38 },
  { name: "Bordj Bou Naama", wilaya: 38 },
  { name: "Bordj El Emir Abdelkader", wilaya: 38 },
  { name: "Khemisti", wilaya: 38 },
  { name: "Larbaa", wilaya: 38 },
  { name: "Lardjem", wilaya: 38 },
  { name: "Layoune", wilaya: 38 },
  { name: "Lazharia", wilaya: 38 },
  { name: "Maacem", wilaya: 38 },
  { name: "Melaab", wilaya: 38 },
  { name: "Ouled Bessem", wilaya: 38 },
  { name: "Sidi Abed", wilaya: 38 },
  { name: "Sidi Boutouchent", wilaya: 38 },
  { name: "Sidi Lantri", wilaya: 38 },
  { name: "Sidi Slimane", wilaya: 38 },
  { name: "Tamalaht", wilaya: 38 },
  { name: "Theniet El Had", wilaya: 38 },
  { name: "Tissemsilt", wilaya: 38 },
  { name: "El Oued", wilaya: 39 },
  { name: "Robbah", wilaya: 39 },
  { name: "Oued El Alenda", wilaya: 39 },
  { name: "Bayadha", wilaya: 39 },
  { name: "Nakhla", wilaya: 39 },
  { name: "Guemar", wilaya: 39 },
  { name: "Kouinine", wilaya: 39 },
  { name: "Reguiba", wilaya: 39 },
  { name: "Hamraia", wilaya: 39 },
  { name: "Taghzout", wilaya: 39 },
  { name: "Debila", wilaya: 39 },
  { name: "Hassani Abdelkrim", wilaya: 39 },
  { name: "Hassi Khalifa", wilaya: 39 },
  { name: "Taleb Larbi", wilaya: 39 },
  { name: "Douar El Ma", wilaya: 39 },
  { name: "Sidi Aoun", wilaya: 39 },
  { name: "Trifaoui", wilaya: 39 },
  { name: "Magrane", wilaya: 39 },
  { name: "Beni Guecha", wilaya: 39 },
  { name: "Ourmas", wilaya: 39 },
  { name: "Still", wilaya: 39 },
  { name: "M'Rara", wilaya: 39 },
  { name: "Sidi Khellil", wilaya: 39 },
  { name: "Tendla", wilaya: 39 },
  { name: "El Ogla", wilaya: 39 },
  { name: "Mih Ouansa", wilaya: 39 },
  { name: "El M'Ghair", wilaya: 39 },
  { name: "Djamaa", wilaya: 39 },
  { name: "Oum Touyour", wilaya: 39 },
  { name: "Sidi Amrane", wilaya: 39 },
  { name: "Aïn Touila", wilaya: 40 },
  { name: "Babar", wilaya: 40 },
  { name: "Baghai", wilaya: 40 },
  { name: "Bouhmama", wilaya: 40 },
  { name: "Chechar", wilaya: 40 },
  { name: "Chelia", wilaya: 40 },
  { name: "Djellal", wilaya: 40 },
  { name: "El Hamma", wilaya: 40 },
  { name: "El Mahmal", wilaya: 40 },
  { name: "El Oueldja", wilaya: 40 },
  { name: "Ensigha", wilaya: 40 },
  { name: "Kais", wilaya: 40 },
  { name: "Khenchela", wilaya: 40 },
  { name: "Khirane", wilaya: 40 },
  { name: "M'Sara", wilaya: 40 },
  { name: "M'Toussa", wilaya: 40 },
  { name: "Ouled Rechache", wilaya: 40 },
  { name: "Remila", wilaya: 40 },
  { name: "Tamza", wilaya: 40 },
  { name: "Taouzient", wilaya: 40 },
  { name: "Yabous", wilaya: 40 },
  { name: "Souk Ahras", wilaya: 41 },
  { name: "Sedrata", wilaya: 41 },
  { name: "Hanancha", wilaya: 41 },
  { name: "Mechroha", wilaya: 41 },
  { name: "Ouled Driss", wilaya: 41 },
  { name: "Tiffech", wilaya: 41 },
  { name: "Zaarouria", wilaya: 41 },
  { name: "Taoura", wilaya: 41 },
  { name: "Drea", wilaya: 41 },
  { name: "Heddada", wilaya: 41 },
  { name: "Khedara", wilaya: 41 },
  { name: "Merahna", wilaya: 41 },
  { name: "Ouled Moumene", wilaya: 41 },
  { name: "Bir Bou Haouch", wilaya: 41 },
  { name: "M'daourouch", wilaya: 41 },
  { name: "Oum El Adhaim", wilaya: 41 },
  { name: "Aïn Zana", wilaya: 41 },
  { name: "Aïn Soltane", wilaya: 41 },
  { name: "Ouillen", wilaya: 41 },
  { name: "Sidi Fredj", wilaya: 41 },
  { name: "Safel El Ouiden", wilaya: 41 },
  { name: "Ragouba", wilaya: 41 },
  { name: "Khemissa", wilaya: 41 },
  { name: "Oued Keberit", wilaya: 41 },
  { name: "Terraguelt", wilaya: 41 },
  { name: "Zouabi", wilaya: 41 },
  { name: "Tipaza", wilaya: 42 },
  { name: "Menaceur", wilaya: 42 },
  { name: "Larhat", wilaya: 42 },
  { name: "Douaouda", wilaya: 42 },
  { name: "Bourkika", wilaya: 42 },
  { name: "Khemisti", wilaya: 42 },
  { name: "Aghbal", wilaya: 42 },
  { name: "Hadjout", wilaya: 42 },
  { name: "Sidi Amar", wilaya: 42 },
  { name: "Gouraya", wilaya: 42 },
  { name: "Nador", wilaya: 42 },
  { name: "Chaiba", wilaya: 42 },
  { name: "Aïn Tagourait", wilaya: 42 },
  { name: "Cherchell", wilaya: 42 },
  { name: "Damous", wilaya: 42 },
  { name: "Merad", wilaya: 42 },
  { name: "Fouka", wilaya: 42 },
  { name: "Bou Ismaïl", wilaya: 42 },
  { name: "Ahmar El Aïn", wilaya: 42 },
  { name: "Bouharoun", wilaya: 42 },
  { name: "Sidi Ghiles", wilaya: 42 },
  { name: "Messelmoun", wilaya: 42 },
  { name: "Sidi Rached", wilaya: 42 },
  { name: "Koléa", wilaya: 42 },
  { name: "Attatba", wilaya: 42 },
  { name: "Sidi Semiane", wilaya: 42 },
  { name: "Beni Milleuk", wilaya: 42 },
  { name: "Hadjeret Ennous", wilaya: 42 },
  { name: "Ahmed Rachedi", wilaya: 43 },
  { name: "Aïn Beida Harriche", wilaya: 43 },
  { name: "Aïn Mellouk", wilaya: 43 },
  { name: "Aïn Tine", wilaya: 43 },
  { name: "Amira Arrès", wilaya: 43 },
  { name: "Benyahia Abderrahmane", wilaya: 43 },
  { name: "Bouhatem", wilaya: 43 },
  { name: "Chelghoum Laid", wilaya: 43 },
  { name: "Chigara", wilaya: 43 },
  { name: "Derradji Bousselah", wilaya: 43 },
  { name: "El Mechira", wilaya: 43 },
  { name: "Elayadi Barbes", wilaya: 43 },
  { name: "Ferdjioua", wilaya: 43 },
  { name: "Grarem Gouga", wilaya: 43 },
  { name: "Hamala", wilaya: 43 },
  { name: "Mila", wilaya: 43 },
  { name: "Minar Zarza", wilaya: 43 },
  { name: "Oued Athmania", wilaya: 43 },
  { name: "Oued Endja", wilaya: 43 },
  { name: "Oued Seguen", wilaya: 43 },
  { name: "Ouled Khalouf", wilaya: 43 },
  { name: "Rouached", wilaya: 43 },
  { name: "Sidi Khelifa", wilaya: 43 },
  { name: "Sidi Merouane", wilaya: 43 },
  { name: "Tadjenanet", wilaya: 43 },
  { name: "Tassadane Haddada", wilaya: 43 },
  { name: "Teleghma", wilaya: 43 },
  { name: "Terrai Bainen", wilaya: 43 },
  { name: "Tessala Lemtaï", wilaya: 43 },
  { name: "Tiberguent", wilaya: 43 },
  { name: "Yahia Beni Guecha", wilaya: 43 },
  { name: "Zeghaia", wilaya: 43 },
  { name: "Aïn Benian", wilaya: 44 },
  { name: "Aïn Bouyahia", wilaya: 44 },
  { name: "Aïn Defla", wilaya: 44 },
  { name: "Aïn Lechiekh", wilaya: 44 },
  { name: "Aïn Soltane", wilaya: 44 },
  { name: "Aïn Torki", wilaya: 44 },
  { name: "Arib", wilaya: 44 },
  { name: "Bathia", wilaya: 44 },
  { name: "Belaas", wilaya: 44 },
  { name: "Ben Allal", wilaya: 44 },
  { name: "Birbouche", wilaya: 44 },
  { name: "Bir Ould Khelifa", wilaya: 44 },
  { name: "Bordj Emir Khaled", wilaya: 44 },
  { name: "Boumedfaa", wilaya: 44 },
  { name: "Bourached", wilaya: 44 },
  { name: "Djelida", wilaya: 44 },
  { name: "Djemaa Ouled Cheikh", wilaya: 44 },
  { name: "Djendel", wilaya: 44 },
  { name: "El Abadia", wilaya: 44 },
  { name: "El Amra", wilaya: 44 },
  { name: "El Attaf", wilaya: 44 },
  { name: "El Hassania", wilaya: 44 },
  { name: "El Maine", wilaya: 44 },
  { name: "Hammam Righa", wilaya: 44 },
  { name: "Hoceinia", wilaya: 44 },
  { name: "Khemis Miliana", wilaya: 44 },
  { name: "Mekhatria", wilaya: 44 },
  { name: "Miliana", wilaya: 44 },
  { name: "Oued Chorfa", wilaya: 44 },
  { name: "Oued Djemaa", wilaya: 44 },
  { name: "Rouina", wilaya: 44 },
  { name: "Sidi Lakhdar", wilaya: 44 },
  { name: "Tacheta Zougagha", wilaya: 44 },
  { name: "Tarik Ibn Ziad", wilaya: 44 },
  { name: "Tiberkanine", wilaya: 44 },
  { name: "Zeddine", wilaya: 44 },
  { name: "Naâma", wilaya: 45 },
  { name: "Mecheria", wilaya: 45 },
  { name: "Aïn Sefra", wilaya: 45 },
  { name: "Tiout", wilaya: 45 },
  { name: "Sfissifa", wilaya: 45 },
  { name: "Moghrar", wilaya: 45 },
  { name: "Assela", wilaya: 45 },
  { name: "8. Djeniene Bourezg", wilaya: 45 },
  { name: "Aïn Ben Khelil", wilaya: 45 },
  { name: "Makman Ben Amer", wilaya: 45 },
  { name: "Kasdir", wilaya: 45 },
  { name: "El Biod", wilaya: 45 },
  { name: "Aghlal", wilaya: 46 },
  { name: "Aïn El Arbaa", wilaya: 46 },
  { name: "Aïn Kihal", wilaya: 46 },
  { name: "Aïn Témouchent", wilaya: 46 },
  { name: "Aïn Tolba", wilaya: 46 },
  { name: "Aoubellil", wilaya: 46 },
  { name: "Beni Saf", wilaya: 46 },
  { name: "Bouzedjar", wilaya: 46 },
  { name: "Chaabat El Leham", wilaya: 46 },
  { name: "Chentouf", wilaya: 46 },
  { name: "El Amria", wilaya: 46 },
  { name: "El Emir Abdelkader", wilaya: 46 },
  { name: "El Malah", wilaya: 46 },
  { name: "El Messaid", wilaya: 46 },
  { name: "Hammam Bouhadjar", wilaya: 46 },
  { name: "Hassasna", wilaya: 46 },
  { name: "Hassi El Ghella", wilaya: 46 },
  { name: "Oued Berkeche", wilaya: 46 },
  { name: "Oued Sabah", wilaya: 46 },
  { name: "Ouled Boudjemaa", wilaya: 46 },
  { name: "Ouled Kihal", wilaya: 46 },
  { name: "Oulhaça El Gheraba", wilaya: 46 },
  { name: "Sidi Ben Adda", wilaya: 46 },
  { name: "Sidi Boumedienne", wilaya: 46 },
  { name: "Sidi Ouriache (Tadmaya)", wilaya: 46 },
  { name: "Sidi Safi", wilaya: 46 },
  { name: "Tamzoura", wilaya: 46 },
  { name: "Terga", wilaya: 46 },
  { name: "Berriane", wilaya: 47 },
  { name: "Bounoura ", wilaya: 47 },
  { name: "Dhayet Bendhahoua", wilaya: 47 },
  { name: "El Atteuf", wilaya: 47 },
  { name: "El Guerrara", wilaya: 47 },
  { name: "El Golea ", wilaya: 47 },
  { name: "Ghardaïa ", wilaya: 47 },
  { name: "Hassi Fehal", wilaya: 47 },
  { name: "Hassi Gara", wilaya: 47 },
  { name: "Mansoura", wilaya: 47 },
  { name: "Metlili", wilaya: 47 },
  { name: "Sebseb", wilaya: 47 },
  { name: "Zelfana", wilaya: 47 },
  { name: "Aïn Rahma", wilaya: 48 },
  { name: "Aïn Tarek", wilaya: 48 },
  { name: "Ammi Moussa", wilaya: 48 },
  { name: "Belassel Bouzegza", wilaya: 48 },
  { name: "Bendaoud", wilaya: 48 },
  { name: "Beni Dergoun", wilaya: 48 },
  { name: "Beni Zentis", wilaya: 48 },
  { name: "Dar Ben Abdellah", wilaya: 48 },
  { name: "Djidioua", wilaya: 48 },
  { name: "El Guettar", wilaya: 48 },
  { name: "El Hamadna", wilaya: 48 },
  { name: "El Hassi", wilaya: 48 },
  { name: "El Matmar", wilaya: 48 },
  { name: "El Ouldja", wilaya: 48 },
  { name: "Had Echkalla", wilaya: 48 },
  { name: "Hamri", wilaya: 48 },
  { name: "Kalaa", wilaya: 48 },
  { name: "Lahlef", wilaya: 48 },
  { name: "Mazouna", wilaya: 48 },
  { name: "Mediouna", wilaya: 48 },
  { name: "Mendes", wilaya: 48 },
  { name: "Merdja Sidi Abed", wilaya: 48 },
  { name: "Ouarizane", wilaya: 48 },
  { name: "Oued Essalem", wilaya: 48 },
  { name: "Oued Rhiou", wilaya: 48 },
  { name: "Ouled Aiche", wilaya: 48 },
  { name: "Oued El Djemaa", wilaya: 48 },
  { name: "Ouled Sidi Mihoub", wilaya: 48 },
  { name: "Ramka", wilaya: 48 },
  { name: "Relizane", wilaya: 48 },
  { name: "Sidi Khettab", wilaya: 48 },
  { name: "Sidi Lazreg", wilaya: 48 },
  { name: "Sidi M'Hamed Ben Ali", wilaya: 48 },
  { name: "Sidi M'Hamed Benaouda", wilaya: 48 },
  { name: "Sidi Saada", wilaya: 48 },
  { name: "Souk El Had", wilaya: 48 },
  { name: "Yellel", wilaya: 48 },
  { name: "Zemmora", wilaya: 48 }
];

const wilayas = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arreridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naâma",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
];